@startuml

skinparam backgroundColor #grey

title: ribbon update server

(*) -> "RibbonClientConfiguration.ribbonLoadBalancer()" as initLB

initLB -> "new ZoneAwareLoadBalancer()" as zoneLB

zoneLB -> "super()" as dynamicLB

dynamicLB --> "DynamicServerListLoadBalancer.restOfInit()"  as initServer

initServer --> "enableAndInitLearnNewServersFeature()"

initServer -left-> "updateListOfServers()" as updateListOfServers

updateListOfServers -left-> "setServersList()" as setServersList

setServersList -left-> "BaseLoadBalancer.setServersList()" as baseSetServerList

baseSetServerList -left-> (*)

@enduml