server:
  port: 8761

spring:
  application:
    name: bookkeeping eureka

eureka:
  instance:
    hostname: localhost
  client:
    # 让服务中心不注册自己
    register-with-eureka: false
    # 是否检索服务
    fetch-registry: false
    # eureka默认空间的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/